// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Users_API.Data;

namespace Users_API.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200722184659_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Users_API.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasMaxLength(36);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasAlternateKey("Email")
                        .HasName("AlternateKey_Email");

                    b.HasAlternateKey("UserName")
                        .HasName("AlternateKey_UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e9acc0f-3062-42f0-8c2c-14adddd0085b"),
                            Email = "user1@mail.com",
                            FirstName = "user1",
                            ImagePath = "",
                            LastName = "user1",
                            Password = "user",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("5e71d6dd-44a8-49e4-8056-8f45a07f0c31"),
                            Email = "user2@mail.com",
                            FirstName = "user2",
                            ImagePath = "",
                            LastName = "user2",
                            Password = "user",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("90f46479-c368-4b8c-9770-62140ab61b36"),
                            Email = "user3@mail.com",
                            FirstName = "user3",
                            ImagePath = "",
                            LastName = "user3",
                            Password = "user",
                            UserName = "user3"
                        },
                        new
                        {
                            Id = new Guid("ce81f20c-c4dc-4bd2-b9a1-d0a906564e6d"),
                            Email = "user4@mail.com",
                            FirstName = "user4",
                            ImagePath = "",
                            LastName = "user4",
                            Password = "user",
                            UserName = "user4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
